### ISSUE TITLE
TS类型编译时检查报错

### ISSUE THREAD

**Issue by wuxudongxd** [pansyjs/react-amap#110]
### 使用环境：
系统：Windows 10 21H2 
node版本：v16.13.0
npm版本：8.1.3
npm源：https://registry.npmmirror.com/

###  问题描述：

我在使用vite作为构建工具进行react-ts项目开发，使用到了@pansy/react-amap。
在运行tsc进行类型检查时@pansy/react-amap发生如下报错：
![QQ截图20211203223136.jpg](https://s2.loli.net/2021/12/03/5MUYtXVi1jH8s2C.jpg)

这里是复现仓库：https://github.com/wuxudongxd/react-amap-demo

复现步骤：

```bash
git clone https://github.com/wuxudongxd/react-amap-demo

cd .\react-amap-demo\

npm install

npm run build
```

### 问题分析：
vite的react-ts模板中tsconfig.json默认将skipLibCheck设为false，对所有声明文件（ *.d.ts）进行了类型检查。
从报错信息来看是 [loadUI](https://github.com/pansyjs/react-amap/blob/main/packages/types/map-ui/index.d.ts#L13)的类型定义没加返回类型；[TileLayer.d.ts ](https://github.com/pansyjs/react-amap/blob/main/packages/types/map/layer/TileLayer.d.ts#L1)导入Layer.d.ts时首字母小写与文件名不一致。

我暂时通过开启skipLibCheck，跳过对声明文件检查来完成编译。对项目不熟悉加上个人能力有限只能先提个issue，作者大大有时间可以看下是否有调整代码的必要。比心❤️

**Comment by wangxingkang** [comment]
好的 我处理一下

**Comment by wangxingkang** [comment]
@wuxudongxd @pansy/amap-types@2.16.2 已修复

**Comment by wuxudongxd** [comment]
好的 👍
