### ISSUE TITLE
marker点的extdata属性未更新

### ISSUE THREAD

**Issue by kkk360** [pansyjs/react-amap#111]
const  markList = [
{ lnt:111.111,lat:111.111 , id:1, name:'zhangsan' },
{ lnt:112.111,lat:114.111 , id:2, name:'lisi' }
]

		{markList.map(item)=>(
			<Marker
						key={item.id}
						position={item.position}
						extData={item}
						offset={[-25, -25]} // 宽高的一半
						events={{
							click: onClickMark1
						}}
				>
		)}
		

如果更修改了markList的数据(增加一条/更换数据) 渲染是正常的, 但是在点击mark的时候 通过e.target.w.extData里的数据是上一次的

**Comment by kkk360** [comment]
https://codesandbox.io/embed/sad-sara-0pj0z?fontsize=14&hidenavigation=1&theme=dark

**Comment by wangxingkang** [comment]
好的 我定位下问题

**Comment by wangxingkang** [comment]
为什么不用 amap 2.0

**Comment by wangxingkang** [comment]
v2  https://react-amap-pansyjs.vercel.app/components/point-mark/marker#extdata  没问题

**Comment by wangxingkang** [comment]
v2  https://react-amap-pansyjs.vercel.app/components/point-mark/marker#extdata  没问题

**Comment by wangxingkang** [comment]
明天看下 v1

**Comment by kkk360** [comment]
好的我明天试一下 地图版本的话我这边是1.4.15 因为要用到中英文就没考虑2的版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangxingkang ***@***.***&gt;
发送时间: 2021年12月7日 23:30
收件人: pansyjs/react-amap ***@***.***&gt;
抄送: jiongsen ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pansyjs/react-amap] marker点的extdata属性未更新 (Issue #111)





 
明天看下 v1
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkk360** [comment]
谢谢您&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangxingkang ***@***.***&gt;
发送时间: 2021年12月7日 23:30
收件人: pansyjs/react-amap ***@***.***&gt;
抄送: jiongsen ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pansyjs/react-amap] marker点的extdata属性未更新 (Issue #111)





 
明天看下 v1
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkk360** [comment]
![image](https://user-images.githubusercontent.com/45529116/145132342-e3201f5f-7ae7-4466-a248-0db0ef457fc9.png)
应该是我写法错误 我获取extdata的方式是e.target.w.extData 使用函数e.target.getExtData()获取的数据是正确的

**Comment by wangxingkang** [comment]
好的 有使用问题及时反馈。1.0 不会积极维护，只有出现BUG才会修复，amap 2.0  应该也是支持多语言的吧
