### ISSUE TITLE
[typescript] GeometryUtil 函数 isPointInRing 未声明

### ISSUE THREAD

**Issue by Xierruisi** [pansyjs/react-amap#133]
### 问题

未声明isPointInRing

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/51395487/161223355-97a0db19-1b58-475e-9a92-909b5392e684.png">

实际上 GeometryUtil 中存在 isPointInRing 函数

<img width="432" alt="image" src="https://user-images.githubusercontent.com/51395487/161223787-bcedd3df-7dfc-45ff-bc42-1cd13d45c11c.png">

### 预期结果

希望能在 `@pansy/amap-types/map/utils/GeometryUtil.d.ts` 补充 isPointInRing 函数声明

**Comment by wangxingkang** [comment]
好的  下个版本提供

**Comment by wangxingkang** [comment]
最新版已添加
