### ISSUE TITLE
在react 18下，地图显示只有框线背景，没有内容。

### ISSUE THREAD

**Issue by zhangcx93** [pansyjs/react-amap#134]
在react 18下，地图显示只有框线背景，没有内容，且对比请求发现少三个请求：
http://vdata.amap.com/nebula/v3?
http://vdata01.amap.com/nebula/v3?
http://vdata02.amap.com/nebula/v3?

通过反复安装17.0.4和18.0.0的react测试稳定复现，且控制台没有任何报错。

**Comment by wangxingkang** [comment]
意思是  v17.0.4 也存在这个问题？

**Comment by zhangcx93** [comment]
> 

17没有问题，那句话的意思就是装17.0.4就好了，装18.0.0就不行了。

**Comment by wangxingkang** [comment]
给个最小复现包吧！

**Comment by zhangcx93** [comment]
我又测了一下，用create-react-app创建的纯react app没有问题，但是用nextjs的有问题，而我的nextjs的其他依赖好像升级到react18以后没有什么问题，现在nextjs默认的react版本也是18。
最小复现：

`npx create-next-app@latest`
更改index.js为：
`import { Map } from "@pansy/react-amap";`

`export default function Home() {`
`  return (`
`     <div style={{ width: "500px", height: "500px" }}><Map mapKey={YOUR_KEY}></Map></div>`
 ` );`
`}`

然后`npm run dev`

**Comment by wangxingkang** [comment]
好  解决了告你

**Comment by zhangcx93** [comment]
有想法了吗？
我尝试编辑next.config.js里，设置reactStrictMode为false，重启，那么地图可以正常显示。
另外对于create-react-app创建的纯React App中，如果在index.js里将<App />放置于<React.StrictMode><React.StrictMode/>中，这个bug也会呈现。应该就是和React的StrictMode有关系。

**Comment by shancheng-77** [comment]
百度地图在react18下也存在这个问题，同样也是去掉严格模式就能显示了

**Comment by wangxingkang** [comment]
暂时先关闭严格模式吧，最近没时间看这个问题

**Comment by wangxingkang** [comment]
@shancheng-77 用的原生的吗  还是别的封装的库

**Comment by wangxingkang** [comment]
目前定位的应该是 Map 组件的问题，具体原因还在排查

**Comment by wangxingkang** [comment]
https://github.com/pansyjs/react-amap/tree/master/examples/next  已解决 可在本示例下看效果 @shancheng-77 @zhangcx93

**Comment by wangxingkang** [comment]
@pansy/react-amap: 2.13.1 => 2.14.0
