### ISSUE TITLE
pathNavigatorStyle 轨迹巡航添加自定义图片添加不了

### ISSUE THREAD

**Issue by qiao236349845** [pansyjs/react-amap#141]
添加content 时，高德给出下面这段代码添加图标，复制到代码里，识别不了
PathSimplifier.Render.Canvas.getImageContent('./imgs/plane.png', onload, onerror),

**Comment by wangxingkang** [comment]
好的 我看下

**Comment by wangxingkang** [comment]
已修复 https://github.com/pansyjs/react-amap/commit/75be29195a010e60f0b0ab528680f615ddfb43af
