### ISSUE TITLE
判断maker是否在当前地图可视区域内

### ISSUE THREAD

**Issue by qixiongduan** [pansyjs/react-amap#142]
运用AMap.GeometryUtil.isPointInRing判断是否在地图可视区域内，                   
                    const bounds = map.getBounds();
                    const NorthEast = bounds.getNorthEast();
                    const SouthWest = bounds.getSouthWest();
                    const SouthEast = bounds.getSouthEast();
                    const NorthWest = bounds.getNorthWest();
                    const mapPath = [NorthEast, SouthEast, SouthWest, NorthWest].map((point) => [
                        point.lng,
                        point.lat,
                    ]);
                    const isPointInRing = AMap.GeometryUtil.isPointInRing(
                        [record.gps.longitude, record.gps.latitude],
                        mapPath,
                    );
                    if (!isPointInRing) {
                        map.setZoomAndCenter(5, [record.origin.longitude, record.origin.latitude]);
                    }
                    mapPath,里经纬度返回超出正常范围，导致无法定位到当前maker](url)，mapPath如下图所示

![lQLPJxZn46WUAEbNAQTNA-qwB2F5KhrcP38Cq0dIakD2AA_1002_260](https://user-images.githubusercontent.com/102567951/173794270-4358bc65-af27-4245-9143-ebcc27a7b648.png)

**Comment by wangxingkang** [comment]
看你的代码都是高德底层的东西，你想问什么？

**Comment by wangxingkang** [comment]
先关闭了，有问题再开 issues
