### ISSUE TITLE
PolylineEditor 折线编辑改变路线时能自动刷新加载

### ISSUE THREAD

**Issue by youbudong** [pansyjs/react-amap#163]
期望PolylineEditor 能监听到地图线路改变时同时 编辑的点也刷新
![image](https://user-images.githubusercontent.com/44150234/200986982-a387f15b-b142-49aa-80d1-cb6228c38788.png)

**Comment by wangxingkang** [comment]
好的 我看下

**Comment by wangxingkang** [comment]
不是太懂你的意思？麻烦给个更详细的描述

**Comment by wangxingkang** [comment]
添加完 详细描述再打开吧
