### ISSUE TITLE
如何使用GLTF模型？

### ISSUE THREAD

**Issue by tianfeng98** [pansyjs/react-amap#177]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/37977609/220549943-4b93cb69-a543-4f35-a940-0735b74ca2ab.png">

高德地图的支持参见[高德地图开放平台-GLTF 模型](https://lbs.amap.com/api/javascript-api/guide/object3d/3d-gltf)

**Comment by wangxingkang** [comment]
待我研究研究

**Comment by wangxingkang** [comment]
看了下 文档  高德  v1   支持相关能力，V2 好像移除了

**Comment by wangxingkang** [comment]
看看V2有没有相应的替换方案 这个库 以 支持  v2 为主 v1 的基本不咋维护了

**Comment by tianfeng98** [comment]
刚刚看了v2升级文档，Object3D暂不支持。2年没有更新了。
不过可以在[GeoHUB自定义地图](https://geohub.amap.com/mapstyle/index)中加载3D模型。

**Comment by wangxingkang** [comment]
@tianfeng98 一定要使用 amap v1 的话 只要拿到 map 对象就可以做高德允许你做任何事，如果有问题，可以提供个最小复现

**Comment by tianfeng98** [comment]
> @tianfeng98 一定要使用 amap v1 的话 只要拿到 map 对象就可以做高德允许你做任何事，如果有问题，可以提供个最小复现

非常感谢，但还是不必麻烦了。
加载3D模型需要创建3D图层
```javascript
// 创建Object3DLayer图层
var object3Dlayer = new AMap.Object3DLayer();
map.add(object3Dlayer);
```
我下午测试，`AMap v2.0`已经没有`Object3DLayer`这个对象了。
必要时我会试试高德提供的跨版本适配器。
![image](https://user-images.githubusercontent.com/37977609/221549716-e0765dbf-6981-4c66-b701-b58b5c1c1a89.png)

**Comment by wangxingkang** [comment]
好的，有问题再沟通

**Comment by wangxingkang** [comment]
先关了 有问题再打开
