### ISSUE TITLE
onComplete不生效

### ISSUE THREAD

**Issue by kkk360** [pansyjs/react-amap#183]
https://codesandbox.io/embed/aged-browser-s28bv7?fontsize=14&hidenavigation=1&theme=dark
你好 我想咨询一下为什么onComplete不生效,是我的使用方式有问题吗

**Comment by wangxingkang** [comment]
今天看一下

**Comment by wangxingkang** [comment]
@pansy/react-amap: 2.15.5 => 2.15.6

**Comment by kkk360** [comment]
多谢多谢 这个库维护了好多年了,比其他的高德库好用多了
