### ISSUE TITLE
PathSimplifier的@pansy/react-amap-ui在vite下安装报错

### ISSUE THREAD

**Issue by hqchqc** [pansyjs/react-amap#185]
![image](https://github.com/pansyjs/react-amap/assets/51051157/0fd6b465-4990-4716-bb2f-852a391787d5)

**Comment by wangxingkang** [comment]
我跟进下

**Comment by wangxingkang** [comment]
@pansy/react-amap-ui: 2.1.15 => 2.1.16

**Comment by hqchqc** [comment]
牛哇 老哥 感谢

**Comment by wangxingkang** [comment]
有问题再反馈
