### ISSUE TITLE
获取RectangleEditor的adjust值错误

### ISSUE THREAD

**Issue by hsulei** [pansyjs/react-amap#186]
事件 adjust 中使用ts bounds 属性无法获取

**Comment by wangxingkang** [comment]
类型错误吗？

**Comment by hsulei** [comment]
![image](https://github.com/pansyjs/react-amap/assets/12029069/fb03ad9d-acb9-4b61-9783-751c58beda55)
这里面interface EventMap<I = BezierCurve> 是不是有问题

**Comment by wangxingkang** [comment]
这个我这两天处理下

**Comment by wangxingkang** [comment]
这个我这两天处理下

**Comment by wangxingkang** [comment]
这个我这两天处理下

**Comment by wangxingkang** [comment]
这个我这两天处理下

**Comment by wangxingkang** [comment]
这个我这两天处理下

**Comment by wangxingkang** [comment]
@pansy/react-amap: 2.15.6 => 2.15.7

**Comment by wangxingkang** [comment]
先关了 有问题 再反馈
