### ISSUE TITLE
是不是APILoader和Map组件不能同时用？

### ISSUE THREAD

**Issue by indomitableXiaoNan** [pansyjs/react-amap#189]
我展示地图之后，想用一下逆地理编码，然后又写了APILoader组件，地图直接不显示了，两种key冲突了吗？

**Comment by wangxingkang** [comment]
Map 内置了 APILoader 组件，只有在不展示地图，需要调用 高德 API 的场景才需要直接使用 APILoader

**Comment by wangxingkang** [comment]
我先关了 有问题再反馈
