### ISSUE TITLE
有没有elasticmarker的开发计划呢？

### ISSUE THREAD

**Issue by cgistar** [pansyjs/react-amap#19]
https://lbs.amap.com/api/javascript-api/reference/overlay#elasticmarker
饿了么的控件中是可以支持的
![image](https://user-images.githubusercontent.com/10128746/115987755-f10ba500-a5e8-11eb-9aa6-eadfcd5d5b86.png)

**Comment by wangxingkang** [comment]
近期会加上去

**Comment by wangxingkang** [comment]
@cgistar  @pansy/react-amap@1.0.14 已添加该组件

**Comment by wangxingkang** [comment]
有时间可以提个PR完善下文档

**Comment by wangxingkang** [comment]
@cgistar 觉得不错，帮忙推广下，万分感谢！

**Comment by cgistar** [comment]
速度真快，谢谢
