### ISSUE TITLE
修改巡航器样式未能生效

### ISSUE THREAD

**Issue by asjdf** [pansyjs/react-amap#192]
根据高德官方Demo尝试修改巡航器尺寸未生效，不确定是否为我代码问题，还请不吝赐教。
https://lbs.amap.com/demo/amap-ui/demos/amap-ui-pathsimplifier/chang-navg-content

下面的案例未能成功运行，我仅粘贴部分关键函数至该库的Demo中，不明白为何无法注册事件。
[样例](https://codesandbox.io/p/sandbox/twilight-darkness-n4g9p4?file=%2FApp.tsx%3A23%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqjsleee00063b6m8ay6h36g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqjsleee00023b6m4jumivff%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqjsleee00033b6m3nnvxwz8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqjsleee00053b6mcic0om3x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqjsleee00023b6m4jumivff%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqjsleed00013b6my3c79qqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqjsm8b000413b6mq9a0o7p1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqjsleee00023b6m4jumivff%2522%252C%2522activeTabId%2522%253A%2522clqjsm8b000413b6mq9a0o7p1%2522%257D%252C%2522clqjsleee00053b6mcic0om3x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqjsleee00043b6m49dfidyx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqjsleee00053b6mcic0om3x%2522%252C%2522activeTabId%2522%253A%2522clqjsleee00043b6m49dfidyx%2522%257D%252C%2522clqjsleee00033b6m3nnvxwz8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqjsleee00033b6m3nnvxwz8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

我本地运行情况：事件处理器成功注册，且修改了巡航器高宽。
<img width="509" alt="image" src="https://github.com/pansyjs/react-amap/assets/22193008/b3a3f833-42b1-4470-b7ef-d8655831d173">

依赖版本：
<img width="274" alt="image" src="https://github.com/pansyjs/react-amap/assets/22193008/fe5e71c8-0d17-4c97-b390-07d246741738">

**Comment by wangxingkang** [comment]
我排查下

**Comment by wangxingkang** [comment]
看描述 1.  无法修改巡航器尺寸  2. 无法绑定事件 ？

**Comment by wangxingkang** [comment]
问题 1 的话 https://amap.xingkang.wang/components/path-simplifier  参考第二个示例 是可以的

**Comment by asjdf** [comment]
哦坏，好像我分享出来的实例和我之前编辑的不太一样，还不太会用 codesandbox。非常抱歉占用您的时间，我目前的需求是想在地图缩放的时候动态调整巡航器大小使其和地图等比例放缩。

然后我之前想通过监听map的事件的方式对巡航器的尺寸进行调整，但是设置后巡航器尺寸没有改变。
<img width="469" alt="image" src="https://github.com/pansyjs/react-amap/assets/22193008/586f98d1-bc91-49f5-832b-b109a982a2d3">

**Comment by wangxingkang** [comment]
好的 我看下

**Comment by wangxingkang** [comment]
@asjdf 简单实现了一版  可以先看下    https://amap.xingkang.wang/components/path-simplifier  第二个示例 缩放地图 zoom 至小于 4

**Comment by wangxingkang** [comment]
有空想下 这块如何实现更优雅，目前 应该满足你的需求了

**Comment by wangxingkang** [comment]
没问题 反馈下 我这发个新版本

**Comment by asjdf** [comment]
看起来满足需求了，感谢！

**Comment by wangxingkang** [comment]
- @pansy/react-amap-ui: 2.1.21 => 2.2.0
 - @pansy/react-amap: 2.19.0 => 2.19.1
