### ISSUE TITLE
InfoWindow设置avoid无效

### ISSUE THREAD

**Issue by SuperBigSniper** [pansyjs/react-amap#195]
看源代码没有对这个属性传到InfoWindow的option里面，希望可以加上这个属性
![image](https://github.com/pansyjs/react-amap/assets/18637424/bedbae73-19c7-4820-947e-4b5341d02b06)
这里面没有avoid属性
![image](https://github.com/pansyjs/react-amap/assets/18637424/dcbfefb6-0a85-4f21-9856-603bd07f105a)
![image](https://github.com/pansyjs/react-amap/assets/18637424/7a41c13c-b909-480d-9bf1-c26400a9f722)

**Comment by SuperBigSniper** [comment]
@chj-damon @aiden-leong @wangxingkang @renovate-bot #196

**Comment by SuperBigSniper** [comment]
#196

**Comment by wangxingkang** [comment]
好的 今天处理下

**Comment by wangxingkang** [comment]
@pansy/react-amap: 2.19.1 => 2.20.0

**Comment by wangxingkang** [comment]
不好意思 这几天没看到  有问题再反馈
