### ISSUE TITLE
在使用Vite打包时会报错，TS7051及TS7010

### ISSUE THREAD

**Issue by langliu** [pansyjs/react-amap#67]
![image](https://user-images.githubusercontent.com/18554111/128710802-d431bfe0-22d1-4a0c-94d4-456c34b03e4c.png)

**Comment by wangxingkang** [comment]
好的 我看下

**Comment by wangxingkang** [comment]
麻烦提供个可复现的包

**Comment by wangxingkang** [comment]
v1.1.2 已修复

**Comment by wangxingkang** [comment]
建议使用 v2 版本
