### ISSUE TITLE
amap-types 缺少了 map-ui 的描述文件

### ISSUE THREAD

**Issue by Brain777777** [pansyjs/react-amap#93]
![1635157528(1)](https://user-images.githubusercontent.com/35163869/138679824-1ca18f36-b37e-4bf1-9c47-3624d46ffad5.jpg)
![1635157545(1)](https://user-images.githubusercontent.com/35163869/138679842-a2e53946-9615-42fe-a652-13713e6dedfc.jpg)

**Comment by wangxingkang** [comment]
好的，忘记更新package.json了

**Comment by wangxingkang** [comment]
不过现在只有轨迹巡航的类型，欢迎PR

**Comment by wangxingkang** [comment]
@pansy/amap-types v2.13.0 已修复

**Comment by wangxingkang** [comment]
@Brain777777 觉得这个库不错 麻烦给个star

**Comment by Brain777777** [comment]
🤖 效率 bro
